<?php

    // +----------------------------------------------------------------------+
    // | RSS for PHPBB                                                        |
    // +----------------------------------------------------------------------+
    // | Copyright (C) Markus Tacker <m@tacker.org>                           |
    // +----------------------------------------------------------------------+
    // | This library is free software; you can redistribute it and/or        |
    // | modify it under the terms of the GNU Lesser General Public           |
    // | License as published by the Free Software Foundation; either         |
    // | version 2.1 of the License, or (at your option) any later version.   |
    // |                                                                      |
    // | This library is distributed in the hope that it will be useful,      |
    // | but WITHOUT ANY WARRANTY; without even the implied warranty of       |
    // | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU    |
    // | Lesser General Public License for more details.                      |
    // |                                                                      |
    // | You should have received a copy of the GNU Lesser General Public     |
    // | License along with this library; if not, write to the                |
    // | Free Software Foundation, Inc.                                       |
    // | 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA               |
    // +----------------------------------------------------------------------+

    /**
    * RSS for PHPBB
    *
    * OPML feed
    *
    * @link http://projects.tacker.org/trac/phpbb-rss
    * @author Markus Tacker <m@tacker.org>
    * @version $Id: opml.php 341 2007-05-15 10:56:54Z m $
    */

    define ('IN_PHPBB', true);
    require_once './common.php';

    // Query
    $sql = 'SELECT f.forum_id, f.forum_name, c.cat_title AS category, c.cat_order FROM ' . FORUMS_TABLE . ' f'
    . ' LEFT JOIN ' . CATEGORIES_TABLE. ' c ON f.cat_id = c.cat_id'
    . ' WHERE f.auth_view = ' . AUTH_ALL
    . ' ORDER BY cat_order ASC, forum_order ASC';
    if (!$result = $db->sql_query($sql)) {
        error('A database error occurred.');
        exit;
    }

    $items = '';
    $data = $db->sql_fetchrowset($result);
    if (is_array($data)) {
        $last_category = '';
        foreach ($data as $item) {
            if ($item['category'] != $last_category) {
                if (!empty($last_category)) {
                    $items .= "    </outline>\n";
                }
                $items .= '    <outline title="' . htmlspecialchars(e($item['category'])) . '">' . "\n";
                $last_category = $item['category'];
            }
            $items .=  '            <outline title="' . htmlspecialchars(e($item['forum_name'])) . '" htmlUrl="' . $forum_url . 'viewforum.' . $phpEx . '?f=' . $item['forum_id'] . '" type="rss" xmlUrl="' . $forum_feed_url . '?fid=' . $item['forum_id'] . '" />' . "\n";
        }
        $items .= "    </outline>\n";
    }

    // Output OPML
    header('Content-type: text/xml; charset=UTF-8', true);
    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    . "<!-- \n"
    . "    OPML generated by RSS for PHPBB, http://projects.tacker.org/trac/phpbb-rss\n"
    . "    Have a nice day.\n"
    . "-->\n"
    . "<opml version=\"1.0\">\n"
    . "    <head>\n"
    . '        <title>' . htmlspecialchars(e($board_config['sitename'])) . "</title>\n"
    . '        <dateCreated>' . date('D, j M Y H:i:s T') . "</dateCreated>\n"
    . "    </head>\n"
    . "    <body>\n"
    . '        <outline title="' . htmlspecialchars(e($board_config['sitename'])) . '" htmlUrl="' . $forum_url . '" type="rss" xmlUrl="' . $forum_feed_url . '" />'
    . $items
    . "    </body>\n"
    . "</opml>\n";

?>